mediumWords = [ "The language spoken by the people by Pakistan is ?",
"The World Largest desert is ?",
"Country that has the highest in Barley Production ?",
"The metal whose salts are sensitive to light is ?",
"The Central Rice Research Station is situated in ?",
"Mount Everest is located in ?",
"Which soil is suitable for agriculture ?",
"Black soils are best suited for the cultivation of ?",
"The device used for measuring altitudes is ?",
"The Gate way of India is in ?",
"The first chairman of the Atomic Energy Commission was ?",
"D.D.T. was invented by ?",
"Which is considered as the biggest port of India ?",
"The gas used for making vegetables is ?",
"The chief ore of Aluminium is ?",
"Sharavati projects is in ?",
"Country that was called as Land of Rising Sun ?",
"Pink city in India is ?",
"The famous Integral Coach Factory(ICF) for the manufacture of railway coaches are situated at ?",
"Deficiency of Iron leads to ?",
"The state which has more deserts in India is ?",
"The headquarters of the coffee board of India is ?",
"The largest fresh water lake in India is ?",
"Name the Governor General who abolished sati in 1829 ?",
"The chemical name of Chloroform is ?",
"The largest river in India is ?",
"The Hindustan Shipyard is located at ?",
"Punjab is famous for ?",
"The oldest literary work available in Tamil was ?",
"Which city is famous for Cotton Industry in TamilNadu ?",
"The state that has the largest number of Cotton textile mills ?",
"The hottest planet in the solar system ?",
"The first Muslim President of the Indian National Congress ?",
"'One People, One State, One leader' was the policy of ?",
"The river that flows through Delhi is ?",
"Name the plant important in sericulture ?",
"The most important river of Orissa is ?",
"Which gas is used for the preparation of Soda water ?",
"Headquarters of UNO are situated at",
"Which crop is sown on the largest area in India?",
"The value of Gold is determined in",
"Gir National Park is situated in",
"Madharasas are the schools of",
"Novak Djokovic is a famous player associated with the game of",
"Who has won the Nobel prize 2017 in economics?",
"Who has won the Nobel Prize 2017 in Literature?",
"'Oscar awards' given for excellent work in the field of",
"Where electricity supply was first introduced in India?",
"For seeing objects at the surface of water from a submarine under water, the instrument used is",
"The state which has the largest number of sugar mills in India is",
"First University in India was founded at",
"Shore temple is located at",
"The highest peak in South India is",
"The person who was also known as Deshbandhu",
"The capital of Uttarakhand is",
"Geet Govind is a famous creation of",
"Which is the largest and the deepest ocean of the world?",
"Which Indian state has the least literacy rate?",
"Which Indian state is inhabited by ‘Jaintiya tribes’?",
"Mount Etna is a famous volcano located in",
"Where is the Tungabhadra sanctuary located?",
"Reserve Bank of India is headquartered at",
"The person who has climbed Mount Everest the most(17 times) is",
"Which Indian state has its maximum area under the forest cover?",
"Which country is known as the ‘Sugar Bowl of the World’",
"The first woman Chief Minister of an Indian State is",
"Which is the third largest desert in the world",
"What is the capital of South Korea?",
"Who is the Chief Executive Officer of Amazon?",
"Which instrument is used for measuring wind speed?",
"Which actress has won the most Oscars?",
"Which country does volleyball originate from?",
"Which famous explorer discovered Cuba?",
"Which is the tallest mountain in the world?",
"Which planet is known as the Red Planet?",
"Which is the largest plateau in the world?",
"What is a baby frog called?",
"Which animal is known as the ‘Ship of the Desert?’",
"From which language is the word ‘ketchup’ derived?",
"Which is the country with the biggest population in Europe?",
"Which English city is often abbreviated to Soton?",
"In which country was Adolf Hitler born?",
"The Great Barrier Reef lies off the coast of which country?",
"What is the largest country in the world?",
"Where would you find the River Thames?",
"Which country is also known as the Netherlands?",
"In which country would you find the Leaning Tower of Pisa?",
"Where would you find the Eiffel Tower?",
"What is the longest river in the world?",
"What is the hottest continent on Earth?",
"What is the capital city of Spain?",
"Which planet is nearest to the Earth?"
];