var meanings = ["someone who offers opposition",
"great coolness and composure under strain",
"in fear or dread of possible evil or harm",
"inherent ability",
"taking heed",
"send away from a place of residence, as for punishment",
"block off with barriers",
"deceive someone about your strength or intentions",
"slightly salty",
"move or swing back and forth",
"the size of something as given by the distance around it",
"confused movement",
"any foodstuff made by combining different ingredients",
"obvious to the eye or mind",
"a tortuous and twisted shape or position",
"speak in response",
"shrewdness as demonstrated by being skilled in deception",
"the remains of something that has been destroyed",
"a hostile challenge",
"skillful in physical movements; especially of the hands",
"the place designated as the end, as of a race or journey",
"decrease in size, extent, or range",
"lack of respect accompanied by a feeling of intense dislike",
"causing dejection",
"force to go away",
"listen without the speaker's knowledge",
"conspicuously and outrageously bad or reprehensible",
"a hot, smoldering fragment of wood left from a fire",
"come out into view, as from concealment",
"consume all of one's attention or time",
"a feeling of annoyance",
"fill with sublime emotion",
"move hesitatingly, as if about to give way",
"seeing ahead; knowing in advance; foreseeing",
"a distinctive odor that is pleasant",
"secret and sly or sordid",
"characterized by effort to the point of exhaustion",
"vigorous and enthusiastic enjoyment",
"the act of dwelling in or living permanently in a place",
"speed up the progress of or facilitate",
"forward movement",
"cause to start burning",
"make free from confusion or ambiguity",
"close in time; about to occur",
"having or showing arrogant superiority",
"talk in a noisy, excited, or declamatory manner",
"technical terminology characteristic of a particular subject",
"make one's way by pushing or shoving",
"extend out or project in space",
"call forth, as an emotion, feeling, or response",
"a small natural hill",
"softly bright or radiant",
"easily influenced",
"come into being; become reality",
"move or cause to move in a winding or curving course",
"marked by extreme care in treatment of details",
"uneasiness about the fitness of an action",
"an impelling force or strength",
"sounded or spoken in a tone unvarying in pitch",
"a large indefinite number",
"gather or bring together",
"give a detailed account of",
"not clearly understood or expressed",
"threatening or foreshadowing evil or tragic developments",
"noticeably or extremely unconventional or unusual",
"stubbornly unyielding",
"having precise or logical relevance to the matter at hand",
"affording an abundant supply",
"existing in possibility",
"a very steep cliff",
"completely free from dirt or contamination",
"overcome or allay",
"one who lives in solitude",
"restore to good health or strength",
"fill something that had previously been emptied",
"offensive to the mind",
"a sum of money paid in compensation for loss or injury",
"destroy property or hinder normal operations",
"a small and inadequate amount",
"move about or proceed hurriedly",
"the absence of mental stress or anxiety",
"friendly and pleasant",
"grave or even gloomy in character",
"an example regarded as typical of its class",
"enduring strength and energy",
"wear off or die down",
"a proud stiff pompous gait",
"move in large numbers",
"a plan for attaining a particular goal",
"brief and to the point",
"allowing light to pass through diffusely",
"surpassing the ordinary or normal",
"unpleasant to look at",
"able to move freely in all directions",
"carefully observant or attentive",
"capable of being wounded or hurt",
"be driven or carried along, as by the air",
"pause or hold back in uncertainty or unwillingness",
"face and withstand with courage",
"a feeling of strong eagerness"
];